@baseUrl = http://localhost:4000/api/v1

GET {{baseUrl}}


//////////////////   users  callback  //////////////////////////////////////

###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "firstName" : "Elia",
    "lastName" : "Schneider",
    "email" : "test@test.com",
    "dateOfBirth" : "12-12-12"
}


###
PUT {{baseUrl}}/users/:userId
Content-Type: application/json

{
    "firstName" : "Elia-Modify",
    "lastName" : "Schneider"
}

###
DELETE {{baseUrl}}/users/:userId
Content-Type: application/json




//////////////////  posts callback  //////////////////////////////////////

###
POST {{baseUrl}}/post
Content-Type: application/json

{
    "category" : "design",
    "titel" : "How to make brand identity",
    "cover": "",
    "content" : "questo e il content del post2"
    
}


###
PUT {{baseUrl}}/post/:postId
Content-Type: application/json

{
    "author" : "SchCreativeDesign",
    "titel" : "How to make brand identity - Modify",
    "content" : "@@@@@@@@@@@@@@@@@@@"
}

###
DELETE {{baseUrl}}/post/:postId
Content-Type: application/json

###
POST {{baseUrl}}/post/67e98a0b1b3e76a47e6f9f4d/comments
Content-Type:  application/json

{
    "text" : "comments hello"
}

###
PUT {{baseUrl}}/post/67e98a0b1b3e76a47e6f9f4d/comments/67ea695948c011495758184b
Content-Type:  application/json

{
    "text" : "comments hello MODIFY"
}

###
DELETE  {{baseUrl}}/post/67e98a0b1b3e76a47e6f9f4d/comments/67ea695948c011495758184b
Content-Type: application/json


###
POST  {{baseUrl}}/singin
Content-Type: application/json
{
    "firstName" : "EXTASY",
    "lastName" : "Molly",
    "email": "molly@molly.com",
    "password" : "MOLLY"
}

###
POST  {{baseUrl}}/login
Content-Type: application/json

 {
    "email": "lasd@mdma.com",
    "password" : "LSD"
 }